services:
  ui:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-https://vyd-api.lambdaanalytics.co/api/}
    restart: unless-stopped
    ports:
      - "127.0.0.1:3100:3000"
    deploy:
      resources:
        limits:
          memory: 64M
