services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: ${VITE_API_URL:-http://192.64.85.84/api/}
    restart: unless-stopped
    ports:
      - "127.0.0.1:3100:3000"
    deploy:
      resources:
        limits:
          memory: 64M
